### ISSUE TITLE
Is comet-llm capable of supporting Flash Attention 2

### ISSUE THREAD

**Issue by rajveer43** [comet-ml/comet-llm#79]
## Description
Flash Attention 2 is a library that provides attention operation kernels for faster and more memory efficient inference and training: 

## References
- [list known implementations](https://github.com/Dao-AILab/flash-attention)

**Comment by jverre** [comment]
Hi @rajveer43 
The Comet LLM SDK is used to log prompts, responses and chains to the Comet platform so that users can easily keep track and review the performance of their LLM models.

I'm not sure I understand how we could integration with Flash Attention 2, can you provide a bit more context in terms of what the integration would entail ?
